### ISSUE TITLE
Get campaign ID and set it to a variable

### ISSUE THREAD

**Issue by jorgeramos1985** [mailjet/mailjet-apiv3-php-simple#138]
Hello,

I'm using this Mailjet repository and I have a problem that I don't know how to solve it. The thing is that that I want to create a campaign from my website and then add HTML content to it. To do so, first of all I have used $response= $mj->newsletter($params); (It works with $response = $mj->Campaigndraft($params); too).

That is working OK, and the campaign is created fine, but then, to execute newsletterDetailContent (or CampaigndraftDetailcontent) we need the ID of the recently created campaign, and save it in a variable (for example $id), to be able to execute CampaigndraftDetailcontent(). I have tried a lot of things and nothing is working....what should I have to do?

$id= (get the ID value of campaignDraftsomehow);

Thank you so much.

**Comment by kmanchikov** [comment]
Hey there, 

If I do understand correctly, once creating a campaign draft through the $Campaigndraft resource you would like to parse the campaign draft ID that you receive as a response and assign it to a variable as you say. I would like to inform that this isn't a Mailjet functionality or an options of ours, instead is a way of interpreting the data that you receive from an API Call and that you would like to do with it. This a basic PHP functionality and depends on how you construct your script and what you do with the response that you receive from Mailjet. 

One way would be the following, 
$campaigndraftid=$response[0]['ID'];

were $campaigndraftid is storing the 'ID' of the campaign draft object created through the process of creating the campaign draft, and then $campaigndraftid could be used instead of the actual 'ID'. 

I hope that this helps, and let me know if you do have any further questions or concerns. 

Best, 
Krassimir

**Comment by jorgeramos1985** [comment]
Hello Krassimir,

Yes, that is what I want. Once I create a campaign using $Campaigndraft, I need to know the ID of that campaign, so that I can use it just after to execute CampaigndraftDetailcontent. Your option seemed OK to me, saving in a variable the ID with this:

$campaigndraftid=$response[0]['ID'];

The problem is that when I execute that line, I get an error even before having a chance to use it in the next resource (Cannot use object of type stdClass as array), that without that line I was not getting.

Do you have any idea why I am getting that message? Thank you

**Comment by kmanchikov** [comment]
Hey, 

Bellow you would be able to find an example that I have used for testing purposes and works like a charm.

```
<?php 

include("mailjet-apiv3-php-simple/src/Mailjet/php-mailjet-v3-simple.class.php");

$apikey = getenv('MJ_APIKEY_PUBLIC');
$apisecret = getenv('MJ_APIKEY_PRIVATE');
$mj = new Mailjet( $apikey, $apisecret );

error_reporting(E_ERROR | E_PARSE);

/*******************************************************
* SENDING NEWSLETTER
********************************************************/

$sender_name="sender name";
$sender_email="example@domain.com";
$id_list=18;
$content_html='html seg [[EMAIL_TO]]';
$content_html="test !!!!";
$subject="subject";
$title="test";


print("\n\nSETTING UP THE NEWSLETTER\n");

$newsletter_id=0;

$params = array(
    "method" => "POST",
    "Locale" => "en_US",
    "Sender" => 0,
    "SenderName" => $sender_name,
    "SenderEmail" => $sender_email,
    "Subject" => addslashes($subject." [[EMAIL_TO]] "),
    "ContactsListID" => $id_list,
    "Title" => "test_title",
);

print_r($params);
$result = $mj->newsletter($params);
if ($mj->_response_code == 201){
	$newsletter_id=$result->Data[0]->ID;	
	echo "\n NEWSLETTER CREATED - ".$newsletter_id."\n";
   	//adding the content
 	$params = array(
	    "method" => "POST",
	    "ID" => $newsletter_id,
	    "Html-part" => $content_html,
	    "Text-part" => $content_text
	);
	$result = $mj->newsletterDetailContent($params);
	if ($mj->_response_code == 201){
		echo "\n NEWSLETTER CONTENT ADDED\n";
		
		//send the newsletter
		$params = array(
		    "method" => "POST",
		    "ID" => $newsletter_id,
		);
		$result = $mj->newsletterSend($params);
		if ($mj->_response_code == 201){
		   echo "\n NEWSLETTER SENT\n";
		   echo "success";
		   print_r($result);
		} else {
		   echo "ERROR NEWSLETTER SENDING- ".$mj->_response_code."\n";
		   var_dump($mj->_response);
		}
	} else {
	   echo "ERROR NEWSLETTER CONTENT- ".$mj->_response_code."\n";
	   var_dump($mj->_response);
	}
} else {
   echo "\n ERROR NEWSLETTER CREATION - ".$mj->_response_code."\n";
   var_dump($mj->_response);
}

?>
```

Just make sure to add your credentials and information in my example so to make it work. Using the following function `$newsletter_id=$result->Data[0]->ID;` you would access the ID. 

CampaignDraft in your case isn't supported since you are using the php-simple wrapper and that is the reason we are using in the example above the newsletter resource and not campaign one. 

Let me know how this one works for you. 

Best, 
Krassimir

**Comment by jorgeramos1985** [comment]
Hello Krassimir,
I've tried your example changing only the credentials and deleting the $result = $mj->newsletterSend($params); (just in case) and it looks like it works.

Now I have to change the content of the campaign with my information, but I guess that will be easy. I'll tell you when I'm finished with that, ok?

Thank you so much

**Comment by kmanchikov** [comment]
Yep, no worries. 

let me know if anything comes up, I would be happy to follow up.

**Comment by jorgeramos1985** [comment]
Hi,

I've changed your script with our information (sender, subjects, list_id, HTML content, etc.) and it's working fine. We can create the newsletter and then add the content with newsletterDetailContent. The created newsletter can be seen in the Mailjet Control Panel, but the problem is that when I go to change something or I want to program a sending date, most of the times I "lose" the HTML content. It's pretty strange, but if I click in the programmed campaign (when it is in draft mode), I've got 3 steps (Configuration, Design and Check & Send, don't I? And for example, when I'm in step 1, I can change the name or list_id without problem, even I can go to step 3 and program rhe campaign without losing anything, but if I go to step 2 or in step 1 I click in "Save & Continue", I go to "design mode" and it does not recognize the HTML code or something and I can only see the different templates that Mailjet offers.

And if I go to "preview" or "continue", I lose everything and I only get an "empty" email in step 3. I don't know if I have explained myself ok or if you know what is going on. If it helps in something, when the campaigns are listed in the Control Panel, the ones that are created with HTML code "manually" have an HTML sign just before the subject, but the ones created with your script don't have that HTML sign, even though if I preview them, the HTML code is OK.

Tell me if you need me to give you some more info. Thank you.

**Comment by jorgeramos1985** [comment]
Ah, I think I got it. I saw that the "newsletter" resource had a field called "EditMode", and I changed it to "html" when it creates, and now I think that in Step 2 the html code it's loaded properly. I will have to run some more tests, but it looks good for now ;)

**Comment by kmanchikov** [comment]
Hey, 

I am glad that all is looking good now and that you are getting more and more confident with our API. The behavior that you have come across in the thread above is an expected one, and indeed it's easily resolved via changing the "EditMode". 

This happens because once a campaign is being created through our API the logic is that you would proceed with adding the content through our API and finally sending the campaign. It's like you would start creating the campaign through our API and continue with editing through the front-end, as this wouldn't make much sense. 

Feel free to reach our Support if you still have any further questions or concerns regarding our API or any other Mailjet product. 

Best, 
Krassimir

**Comment by jorgeramos1985** [comment]
Hello,
Yeah, everything seems to be fine. Changing EditMode to HTML solved the other problem I found, and after that I was able to use newsletterSchedule and newsletterSend. Thank you very much.

I will close this issue, because it's solved.
