### ISSUE TITLE
When I add a new sender address I don't receive the email confirmation

### ISSUE THREAD

**Issue by anardil** [mailjet/mailjet-apiv3-php-simple#29]
Hello,

I try to add new sender address by the API: 
Here my params:

		    $params = array(
		        "method" 		=> "POST",
		        "Email" 		=> $list['sender_email'],
		        "EmailType" 	=> 'bulk',
		        "Name"			=> $list['sender_name'],
		    );
	
		    $result = $mj->sender($params);	

The new sender address has been inserted but I don't receive the email to activate this sender.
I have to go the web interface and ask an activation for this sender to receive the email confirmation.

Could you help me ?
Thanks.

**Comment by arnaudbreton** [comment]
Hi,

I'm happy to announce you that this issue is now solved on our side! From now, when you POST a new sender using the API, a confirmation email will be send. 

For further questions or if you experience issues with this on your account, don't hesitate to contact our [support team](https://mailjet.com/support/ticket)

Thanks for your patience and sorry for the disturbance this issue may have caused.
Regards,
Arnaud.
