### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by webiummedia** [mailjet/mailjet-apiv3-php-simple#43]
Hey guys nice job on this class. 
I need to integrate it to one of my projects and i am having a few issues ...

When i create an email for the first time it's added to the archive ... then i retreive the ID from the createContact() result to add the contcat to the contact list ... Works great ... But if i delete the user from the list and try again, the createContact() returns an error ... and no output ... So how am i supose to add him to the list? 

    if ($_POST[newsletter_form]){
        
        // Adding the user to mailjet
        $contact = createContact($_POST[courriel], $_POST[nom]);
        
        // If it worked we should have an ID
        if ($contact[Data][0][ID]){
            // Use the ID to add the user to list 1
            $list = addContactToList($contact[Data][0][ID], 1);
        }else{
            // The user was already added to the archive section
            // How can i get the ID that was assigned to his email?
            // ???????????????????????????????
        }
    
    }

I started working on my own function but so fare it's not working ... Do i need to edit the class?

    function getcontact($email) {
        $mj = new Mailjet();
        $params = array(
            "method" => "POST",
            "contact" => "$email"
        );
    
        $result = $mj->contactInfos($params);
        $result = json_decode(json_encode($result),true);
    
        if ($mj->_response_code == 201)
           $result[status] = "1";
        else
           $result[status] = "0";
    
        return $result;
    }

An other issue i am having is allowing a user to delete it self from a contact list providing only his email ... I did not find any function for that. Please help

I tryed making this function but it's not working.

    function deletecontact($id, $email) {
        $mj = new Mailjet();
        $params = array(
            'method' => 'POST',
            'contact' => $email,
            'id' => $id
        );
    
        $result = $mj->listsRemoveContact($params);
        $result = json_decode(json_encode($result),true);
    
        if ($mj->_response_code == 201)
           $result[status] = "1";
        else
           $result[status] = "0";
    
        return $result;
    }

**Comment by arnaudbreton** [comment]
Hey Patrick,

Thanks for reaching out and provide us with a detailed description of your problem.
Sorry to hear that you had troubles using our API.

I assume here that your `createContact` method calls our `contact` API ressource to create contact in our system, right? If it's the case, as [described in our documentation](http://dev.mailjet.com/guides/contact-guide/#deleting-contacts), you can't delete a contact. This is on purpose to be sure we can provide you with the history of messages, even for emails not assigned to contacts lists and also when using the transactional system.

Back to your first example, I would suggest to change the way to proceed, by try-ing first to retrieve a contact (similar to what you did with the `getContact` function) and if it does not exist, create it. It gives the following code:
```php
if ($_POST[newsletter_form]){

    // Does the user already exist at Mailjet?
   $params = array(
      "method" => "VIEW",
      "Email" => $_POST[courriel]
   );
    $contact = $mj->contact($params);

    // If it worked we should have an ID
    if ($contact[Data][0][ID]){
        // Use the ID to add the user to list 1
        $list = addContactToList($contact[Data][0][ID], 1);
    }else{
       // Create the contact
       $contact = createContact($_POST[courriel], $_POST[nom]);
    }
}
```

To add/remove a contact in a list, I invite you to take a look at the [`listrecipient`](http://dev.mailjet.com/email-api/v3/listrecipient) API ressource, which represents the link between a [`contactslist`](http://dev.mailjet.com/email-api/v3/contactslist/) and a [`contact`](http://dev.mailjet.com/email-api/v3/contact/).
According to our documentation, since the `listrecipient` ressource has `ContactALT` and `ListALT` properties, you can identify this link by using the contact's email and the list's name (instead of ID).
This is this ressource which should be used in your `addContactToList` method.

Based on that, and since - as said above - you can't delete a contact in the system, your `deleteContact` (here `deleteContactFromList` would be more explicit) should be defined as below:
```php
function deleteContactFromList($listId, $email) {
    $mj = new Mailjet();
    $params = array(
        'method' => 'DELETE',
        'ContactALT' => $email,
        'ListID' => $listId
    );

    $result = $mj->listRecipient($params);
    $result = json_decode(json_encode($result),true);

    if ($mj->_response_code == 201)
       $result[status] = "1";
    else
       $result[status] = "0";

    return $result;
}
```

Hope it helps.

Don't hesitate to reach us again if you have further questions or if I missed something.
You can also find additional examples in our [Working with Contacts guide](http://dev.mailjet.com/guides/contact-guide/) and [Working with Lists guide](http://dev.mailjet.com/guides/contact-list-guide/).

Best.

**Comment by webiummedia** [comment]
Wow thanks arnaudbreton! I am pleased to see how well responded my issue was. It solved my problems. Before i close this issue, is there any chance you can add deleteContactFromList() and getContact() to the readme? You have an exemple on how to delete a contact list but not a user. And there was no exemple on how to get a users data based on his email.

Great job, keep it up!

**Comment by arnaudbreton** [comment]
Patrick,

Thanks for the quick feedback. Glad to see everything's OK for you now!

You're right we should improve our README. I'll take care of it ASAP.

Best.
Arnaud.

**Comment by webiummedia** [comment]
Sounds good. Have a nice week end!
