### ISSUE TITLE
Getting alle unsubscribed contacts of list

### ISSUE THREAD

**Issue by wfabian** [mailjet/mailjet-apiv3-php-simple#53]
Hi,
I like to get all unsubscribed contacts of a list.

I tried something like this:
function mailjetGetUnsubscribedContactsFromList(Mailjet $mj, $listID) {
    $params = array(
        "method" => "GET",
        "ListID" => $listID,
        "IsUnsubscribed" => true
    );
    $result = $mj->listrecipient($params);
    if ($mj->_response_code == 201)
        return "Okay";
    else
        echo "error - ".$mj->_response_code;
}

But the contact-ID is for listrecipient-function mandatory, too.
Is there anyway to solve my problem?

**Comment by hristo-todorov** [comment]
Hi @wfabian,

In order to get a list of all unsubscribed contacts of a list you need to filter the contact list. Here's a code snippet that does this:

``` php 
function getUnsubscribedContactsFromList(Mailjet $mj, $listID) {
	$params = array(
		"method" => "GET",
		"ContactsList" => $listID,
		"Unsub" => true
	);
	
	$result = $mj->listrecipient($params);
	
    if ($mj->_response_code == 200)
       echo "success - got unsubscribed contact(s) ";
    else
       echo "error - ".$mj->_response_code;
   
	return $result;   
}
```

I hope this helps. Don't hesitate to contact me if you need more help,

This code snippet and more could be found at https://github.com/mailjet/mailjet-apiv3-php-simple/blob/master/README.md

For more contact list filters you can have a look at our reference guide - http://dev.mailjet.com/email-api/v3/listrecipient/#filters

Cheers!

**Comment by wfabian** [comment]
Thank's again, that solved my problem.

**Comment by GuillaumeBadi** [comment]
### Hey @wfabian :airplane:

We just released a [new PHP API wrapper](https://github.com/mailjet/mailjet-apiv3-php).
It is now more PHP-ish (including namespace, PSR-0 compliance, and globally a better architecture).
All it requires is PHP 5.4

In addition to our [API Guides](http://dev.mailjet.com/guides/?php), we would be happy to help you get started with it.

Guillaume, from Mailjet!
