### ISSUE TITLE
Laravel 5 integration

### ISSUE THREAD

**Issue by sboo** [mailjet/mailjet-apiv3-php-simple#72]
Hi,

I created this [package for Laravel 5](https://github.com/sboo/laravel5-mailjet), which also includes this library. Unfortunately I can't just 'require' it with composer, because your class is not namespaced.

1. Would you mind putting your example class into a namespace? Or should I leave it as it is?

2.  Feel free to add the library to your plugin list on http://dev.mailjet.com/email-api/v3/apikey/

Cheers,
Ramon

**Comment by arnaudbreton** [comment]
Hi @sboo, 

Thanks for reporting this and sharing your work! 
Would be great if you could open a Pull Request to fix this. Otherwise, we'll have a look at this ASAP.

**Comment by JMFns4LmutumIT** [comment]
:)


--
Regards, cyaL'8R, salutations, Cdt,

[JMFrambourt]-{mutum board} mutum.fr "Plus on partage, plus on possède!" #Consocollab #Paris
☆IT Dept. Resp.
☆IT/IS Direction
Corp@ -> jm.frambourt@mutum.fr
Pers@1 -> jm@frambourt.com
Pers@2 -> jm@televasion.fr
Pers@3 -> contact@life-in-space.com
{+×○□ns4L}

╔═..·´¯`·-> Mem.════════════════╗
 [Apple II assembleur 1978 Php 1996
  depl. web FR - multi lg de 78 à 2010
 [TeleVasion.com founder 2000
 [2.000 ppls multi-trained 1990-2002
 [UJJEF 2002 Meilleur web entreprise 
 [Conso. tech 180mds CA Veolia eau
╚══════════════════════════╝
Perso W
http://www.frambourt.com
http://www.life-in-space.com
http://www.televasion.fr

Corp. cell/mob -> +33681563924
Pers. cell/mob -> +33681563924
--------
Envoyé depuis mobile
Sent by cell

~ Confiental - thank you ~

<div>-------- Message d'origine --------</div><div>De : Arnaud BRETON <notifications@github.com> </div><div>Date :04/11/2015  4:47 PM  (GMT+01:00) </div><div>A : mailjet/mailjet-apiv3-php-simple <mailjet-apiv3-php-simple@noreply.github.com> </div><div>Objet : Re: [mailjet-apiv3-php-simple] Laravel 5 integration (#72) </div><div>
</div>Hi @sboo,

Thanks for reporting this and sharing your work! 
Would be great if you could open a Pull Request to fix this. Otherwise, we'll have a look at this ASAP.

**Comment by sboo** [comment]
Done. travis phpunit test fails because of missing env variables ofc, but the changes work
