### ISSUE TITLE
Duplicate a sent newsletter

### ISSUE THREAD

**Issue by aminebk** [mailjet/mailjet-apiv3-php-simple#76]
Hi,

There is a method to duplicate a sent newsletter? I checked all doc here, but I didn't see how to do it.
http://dev.mailjet.com/email-api/v3/newsletter-detailcontent/

It seems it was before in v1 of API
https://app.mailjet.com/docs/api/message/duplicatecampaign

Thanks for any helping

**Comment by arnaudbreton** [comment]
Hi @aminebk,

First of all, thanks for your interest in Mailjet API!

In order to achieve this, you can use the `DuplicateFrom` in a POST request with the following payload '{"Status":0,"EditMode":"html"}'. Using curl, the call will look like this:
```shell
curl -i -X POST --user "$MJ_API_KEY:$MJ_API_SECRET" $BASE_URL/v3/REST/newsletter?DuplicateFrom=:id_to_duplicate -H 'Content-Type: application/json' -d '{"Status":0,"EditMode":"html"}'
```

Unfortunately, at the moment our wrapper doesn't support filters on POST request (only GET). We'll update it to support this and will let you know as soon as it's done. Meanwhile, we would be more than happy to integrate a Pull Request on this.

Sorry for the inconvenience,
Arnaud.

**Comment by arnaudbreton** [comment]
Hi @aminebk,

If this issue is now solved for you, could you please close it? Don't hesitate to reach us again for further explanations, or to open a new issues if needed.

Best

**Comment by GuillaumeBadi** [comment]
### Hey @aminebk :airplane:

We just released a [new PHP API wrapper](https://github.com/mailjet/mailjet-apiv3-php).
It is now more PHP-ish (including namespace, PSR-0 compliance, and globally a better architecture).
All it requires is PHP 5.4

In addition to our [API Guides](http://dev.mailjet.com/guides/?php), we would be happy to help you get started with it.

Guillaume, from Mailjet!
